// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqtdghrbwgrzkhysxbia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxdGRnaHJid2dyemtoeXN4YmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTI4MTgsImV4cCI6MjA3MzgyODgxOH0.8IduJiIZE0db9My-nQ0be8U4rAM-reVVlFOJS8e6sFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});